language: ruby
rvm:
  - 2.2.3
postgres:
  adapter: postgresql
  database: jeanie
  username: postgres
before_script:
  - "psql -c 'create database jeanie;' -U postgres"
  - "bundle exec rake db:migrate"
